### ISSUE TITLE
Shorthand properties with dynamic values when expanded produce invalid/not-working CSS

### ISSUE THREAD

**Issue by d4rkr00t** [atlassian-labs/compiled#1331]
**Describe the bug**
Shorthand properties with dynamic values, when expanded, produce invalid/not-working CSS. E.g. padding → padding-top, padding-right, padding-bottom,  padding-left.

**To Reproduce**
Component:

```js
export const Component = ({ moarPadding }) => {
  return (
    <div
      css={{
        padding: moarPadding ? "6px 18px 6px 32px" : "6px 18px",
      }}
    />
  );
};
```

Produces:
```js
var _4 = "._19bv1m5j{padding-left:var(--_1bqd591)}";
var _3 = "._n3td1m5j{padding-bottom:var(--_1bqd591)}";
var _2 = "._u5f31m5j{padding-right:var(--_1bqd591)}";
var _ = "._ca0q1m5j{padding-top:var(--_1bqd591)}";
export var Component = function Component(_ref) {
  var moarPadding = _ref.moarPadding;
  return /*#__PURE__*/React.createElement(CC, null, /*#__PURE__*/React.createElement(CS, null, [_, _2, _3, _4]), /*#__PURE__*/React.createElement("div", {
    className: ax(["_ca0q1m5j _u5f31m5j _n3td1m5j _19bv1m5j"]),
    style: {
      "--_1bqd591": ix(moarPadding ? "6px 18px 6px 32px" : "6px 18px")
    }
  }));
};
```

Which results in CSS:

```css
._19bv1m5j {
  padding-left: 6px 18px 6px 32px; /* <- var replaced with an actual value, originally was 'var(--_1bqd591)' */
}
```

**Expected behavior**
```css
._19bv1m5j {
  padding-left: 32px;
}
```

**Additional context**
Repo: https://github.com/d4rkr00t/compiled-padding-issue-repro
