### ISSUE TITLE
Improve error message when using css attribute without css(...) function call

### ISSUE THREAD

**Issue by dddlr** [atlassian-labs/compiled#1495]
This produces a runtime error:

```css
import { css, styled } from '@compiled/react';

const styles = css({ color: 'yellow' });

const MyComponent = styled.div({});
const MyOtherComponent = ({ someParameter, children }) => <MyComponent css={someParameter || styles}>{children}</MyComponent>;

<MyOtherComponent someParameter={{ color: 'yellow', fontSize: '50px' }}>hello worilnd</MyOtherComponent>
```

```
Uncaught TypeError: classNames[0].indexOf is not a function
```

<img width="564" alt="Screenshot 2023-08-23 at 11 41 07" src="https://github.com/atlassian-labs/compiled/assets/2908767/5cabafac-1625-4a47-aed5-e29e3121194c">

This is because `{ color: 'yellow', fontSize: '50px' }` should be wrapped in a `css( ... )` function call. The correct(er) syntax, which does work with Compiled, would be something like this:
```tsx
<MyOtherComponent someParameter={css({ color: 'yellow', fontSize: '50px' })}>hello worilnd</MyOtherComponent>
```

We should change the error message so that it should be more helpful and direct them to using the correct syntax. For example, we can tell the user that they are missing a css(...) function call around the `{ color: 'yellow', fontSize: '50px' }` object.

This would probably not be practical to add to `@compiled/eslint-plugin`, because ESLint runs on each file individually and thus cannot detect usages of `MyOtherComponent` across multiple files. Perhaps we can add this to `@compiled/babel-plugin` so that we get a build time error, not a runtime error
