### ISSUE TITLE
RFC: Compile time media queries

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#165]
Inspired by this tweet: https://twitter.com/elyktrix/status/1252663976334438401?s=20

This is to take the boiler plate out and to stream line the use as well. (Mobile first!)

Define what media queries you want in your conf object (API tbd):

```js
options: {
  media: {
    small: 400,
    medium: 800,
    large: 1000
  }
}
```

Then use in your CSS

```js
css`
  font-size: [12px, 18px, 24px, 30px];
`
```

Which results in the generated CSS

```css
.cc-123abc {
  font-size: 12px;

  @media screen and (min-width: 400px) {
    font-size: 18px;
  }

  @media screen and (min-width: 800px) {
    font-size: 24px;
  }

  @media screen and (min-width: 1000px) {
    font-size: 30px;
  }
}
```

We should also try to optimize the creation of media queries. If we have multiple in a block:

```js
css`
  font-size: [12px, 18px, 24px, 30px];
  color: [blue, red];
`
```

We place them accordingly:

```css
.cc-123abc {
  font-size: 12px;
  color: blue;

  @media screen and (min-width: 400px) {
    font-size: 18px;
    color: red;
  }

  @media screen and (min-width: 800px) {
    font-size: 24px;
  }

  @media screen and (min-width: 1000px) {
    font-size: 30px;
  }
}
```

We need to figure out an API that works when wanting to target only a specific subset.
We could just duplicate and then compress?

```js
css`
  font-size: [24px, 24px, 24px, 30px];
`
```

```css
.cc-123abc {
  font-size: 24px;

  @media screen and (min-width: 1000px) {
    font-size: 30px;
  }
}
```

---

This can also relate to simplifying selectors as well, ala https://twitter.com/james_k_nelson/status/1257499618981507072
