### ISSUE TITLE
Conditionally applied style rules

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#278]
Because of our early pivot to atomic CSS at "baked in" time - we're empowered to support this kind of behaviour - which will work very consistently!

**Style declarations**

You can conditionally apply mixins like so:

```jsx
<div 
  css={{
    color: 'blue',
    ...props.isPrimary && { fontSize: 15, fontWeight: bold },
  }}
/>

<div 
  css={`
    color: blue;
    ${props.isPrimary && { fontSize: 15, fontWeight: bold }};
  `}
/>

styled.div`
  color: blue;
  ${props.isPrimary && { fontSize: 15, fontWeight: bold }};
`;

styled.div({
   color: 'blue',
  props => props.isPrimary && { fontSize: 15, fontWeight: bold },
});
```

Which would become (simplified):

```css
.color-blue { color:  blue }
.font-size-15 { font-size: 15px }
.font-weight-bold { font-weight: bold }
```

```jsx
<div className={ax(['color-blue', props.isPrimary && 'font-size-15 font-weight-bold'])} />
```

**Css prop array**

```jsx
const red = { color: 'red', textSize: 12 }; 
<div  css={[isDanger && red, { background: 'blue' }]} />;
```

```css
.color-red { color: red }
.background-blue { background: blue }
```

```jsx
<div className={ax([isDanger && 'color-red text-size-12', 'background-blue'])} />
```

Same principle would apply to the class names API `css` prop.

## Testing notes

- Logical expression single (`isPrimary && css`)
- Logical expression multiple (`isPrimary && selected && css`)
- Conditional expression (`isPrimary ? css : otherCss`)
- Array with expressions (`css([isPrimary ? css : otherCss])`)
- All above with CSS prop
- All above with Styled
- All above with ClassNames
