### ISSUE TITLE
PostCSS atomic plugin

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#286]
This plugin should take a CSS declaration and outut it as atomic declarations.

**Input**

```css
display: block;
color: blue;
```

**Output**

```css
.{group}{value} {
  display: block;
}
.{group}{value} {
  color: blue;
}
```

Look at the spike implementation here: https://github.com/atlassian-labs/compiled/pull/274/files#diff-3d0e3948c146d9c40c8c173d78fda7e0

Each declaration should be made up of two hashes, a group, and a value, each 4 characters long.

```
.{grouphash}{valuehash}
```

We’re going to use the group as a unique identifier to make overrides work correctly.

A group is defined as:

```
{atrules}{selectors}{propertyname}
```

A value is defined as:

```
{value}
```

**At rules**

Ensure they're combined.

```css
display: block;

@media (min-width: 500px) {
  display: flex;
  color: red;
}
```

```css
.{group}{value} { display: block }
@media (min-width: 500px) {
  .{group}{value} { display: flex }
  .{group}{value} { color: red }
}
```

**Autoprefixing**

Properties that need autoprefixing shouldn't create duplicate atomic entries.

```css
display: grid;
```

```css
.{group}{value} {
  display:-ms-grid;
  display:grid
}
```

**Duplicate declarations**

We should remove any fallback values and lean on autoprefixer from above to do the work if its needed.

```css
display: block;
display: flex;
```

```css
.{group}{value} {
  display:flex
}
```

**Testing notes**

We need to make sure all kinds of combinations of selectors work.
 
- [x] top level property
- [x] properties in nested selectors
- [x] top level property inside an at rule
- [x] properties in nested selectors in an at rule
- [x] should callback with all created class names to be used later on
- [x] ensure if any property that needs prefixing has it in the atomic declaration

## Follow up tasks

We need to keep this ticket in a reasonable size.

**Shorthands**

Shorthand properties need to be blown up. For a list see: https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties. This should be its own PostCSS plugin.

```diff
-background: black;
+background-color: black;
```

Q: This means that when values are omitted should we generate their initial values as per spec? Probably. But we could also not.

**Nested at rules**

We also need to support nested at rules, see: https://css-tricks.com/can-you-nest-media-and-support-queries/. We'll implement it later.
