### ISSUE TITLE
Merge same nested media queries

### ISSUE THREAD

**Issue by pgmanutd** [atlassian-labs/compiled#316]
We have to merge cases like below and ensure it follows lvfha ordering (if pseudo classes are present)

More details: [https://github.com/atlassian-labs/compiled/issues/290#issuecomment-706791171](https://github.com/atlassian-labs/compiled/issues/290#issuecomment-706791171)

```css
@media (max-width: 400px) {
  @media (max-width: 300px) {
    :active { color: red; }
    :focus { color: pink; }
  }

  @media (max-width: 300px) {
    :hover { color: green; }
    :visited { color: black; }
    :link { color: yellow; }

    @media (max-width: 200px) {
      :active { color: red; }
      :focus { color: pink; }
    }

    @media (max-width: 200px) {
      :hover { color: green; }
      :visited { color: black; }
      :link { color: yellow; }
    }
  }
}

will become

@media (max-width: 400px) {
  @media (max-width: 300px) {
    :link { color: yellow; }
    :visited { color: black; }
    :focus { color: pink; }
    :hover { color: green; }
    :active { color: red; }

    @media (max-width: 200px) {
      :link { color: yellow; }
      :visited { color: black; }
      :focus { color: pink; }
      :hover { color: green; }
      :active { color: red; }
    }
  }
}
```
