### ISSUE TITLE
Negative numbers breaking property expanding

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#400]
```js
export const Wrapper = styled.section`
    margin: 0 -${props => props.gridSize * 5}px ${props => props.gridSize * 4}px -${props => props.gridSize * 5}px;
`;
```

Results in

```css
--_1l3fmvo: 0 -40px;
--_gbo7pc: 32px;

._18u0vsak {
    margin-left: var(--_gbo7pc);
}

._otyr1xn1 {
    margin-bottom: var(--_1l3fmvo);
}

._2hwxvsak {
    margin-right: var(--_gbo7pc);
}

._19pk1xn1 {
    margin-top: var(--_1l3fmvo);
}
```

Margin left is wrong.
