### ISSUE TITLE
Importing through star syntax does not statically evaluate

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#630]
**Describe the bug**
Importing through star syntax does not statically evaluate.

**To Reproduce**

```js
import { styled } from '@compiled/react';
import * as colors from './imports/colors';

export const Blue = styled.span`
  color: ${colors.blueviolet};
`;
```

```css
._syaz57xd{color:var(--_103kgnr)}
```

Changing to extracting the values individually works.

```js
import { styled } from '@compiled/react';
import { blueviolet }  from './imports/colors';

export const Blue = styled.span`
  color: ${blueviolet};
`;
```

```css
._syazmu8g{color:blueviolet}
```

**Expected behavior**
Values are statically evaluated.
