### ISSUE TITLE
Unused components have their styles extracted

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#631]
**Describe the bug**
When #561 is merged it also will introduce a bug. "Unused components have their styles extracted"

**To Reproduce**

```js
import '@compiled/react';

export const Orange = () => <div css={{ color: 'orange', border: '2px solid orange' }} />;
```

```js
import { Orange } from './imports/css-prop';
// Unused
```

```css
._19itgh5a{border:2px solid orange}
._syazruxl{color:orange}
```

**Expected behavior**
The unused component should not have its styles extracted.
